FROM python:3.13.3
WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

# Add Broadcom (WSS) client certificate to the systems /etc/ssl/certs/ca-certificates.crt file
ADD ./CertEmulationCA.crt /usr/local/share/ca-certificates/CertEmulationCA.crt
RUN update-ca-certificates

# point to the updated certs for python and openssl
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

RUN pip config set global.cert /etc/ssl/certs/ca-certificates.crt

# Copy just requirements so we don't have to re-do pip install every time code changes
# then run pip install
COPY ./requirements/requirements.txt /app/requirements.txt
RUN pip install  --no-cache-dir -r /app/requirements.txt

# Install for pipeline
RUN pip install kfp==2.10.1

# Copy the rest of the code....skipping directories that may contain data
COPY ./src /app/src

# set python path and working dir 
ENV PYTHONPATH=/app/src
WORKDIR /app/src

# run the flask app!
# host must be 0.0.0.0 for cloud run to pick it up.
# CMD ["python"]
ENTRYPOINT ["sh", "-x", "gunicorn.sh"]